### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ben432rew** [erikasland/RubyBank#7]
I get this error when attempting to follow the readme instructions:

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- sqlite3 (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/computeruser/programming/RubyBank/model.rb:1:in `<top (required)>'
    from controller.rb:2:in `require_relative'
    from controller.rb:2:in `<main>'
```

**Comment by ben432rew** [comment]
Might need some gems?
